### ISSUE TITLE
Issue to run PyGeM test

### ISSUE THREAD

**Issue by Thmbzh** [mathLab/PyGeM#179] opened 2020-03-25 17:25 UTC
Hello,
For an internship I have to use PyGeM library. I downloaded it an go through the installation file without any problems (installed Anaconda3, all packages needed). But when I wanted to run the 'test.py' file, I had the error 'ModuleNotFoundError (No module named 'OCC.Core')'
I used the command line to install packages :
conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.17 python=3.6
I followed the instructions on the 'Read me' file to be sure to get it working well.
It has been 2 days I searched online how to fixed it but I'm kinda lost and that's why I'm requesting your help.
I precise I'm not familiar with programming or coding.
Thank you in advance

Thomas B

**Comment by Thmbzh** [comment] 2020-03-27 11:07
I eventually succeded to run the test.py file by following the steps in the '.travis.yml' file. 
One thing is that I have to go through the following commands every time to launch it with success :
-chmod
-export
-hash -r
-source activate test
-python3 test.py

If somebody knows how to avoid these steps in the future, very much appriciated.

**Comment by mtezzele** [comment] 2020-03-27 11:10
Dear Thomas, 
sorry for the late reply. In these days Nicola completed the porting to the new version of OCC, so the reason why the readme is not updated. We are sorry. There will be some other changes in the near future.

**Comment by Thmbzh** [comment] 2020-03-27 11:18
No worries, I know these days are kinda difficult for everyone.
I will look closely to the changes.

Thank you for your answer !

**Comment by ndem0** [comment] 2020-07-07 16:13
It is a bit difficult to understand what was the problem. The error you got makes me assuming you were using the latest version of PyGeM with the old version (0.17) of pythonocc-core, and this creates the problem. I updated the README in #202, so now you should be able to easily run the tests. Sorry for  the inconvenience and please let us know if you still have some problems regarding the tests.

**Comment by Thmbzh** [comment] 2020-07-08 08:04
I think it was indeed a problem of versions. I installed it according to the '.travis.yml' file and put these commands in the bashrc file to run it :
 -chmod
-export
-hash -r
-source activate test

I haven't had any issues since then, and it works perfectly. Succed to finish my internship mission this day thanks to it !

**Comment by ndem0** [comment] 2020-07-10 08:09
We are glad to read this! Since the problem is solved, I close the issue.

**Closed by ndem0** 2020-07-10 08:09 UTC
